### ISSUE TITLE
Algod Algorand Configuration

### ISSUE THREAD

**Issue by hershellayton95** [ActivaDigital-it/algon#12]
**Issue 1/2**
The default connection doesn't work.

**Solution 1/2**
Set `DNSBootstrapID: testnet.algorand.network`

**Issue 2/2**
During bootstrapping, if node catchup `doesn't work`, there are many logs, and the storage volume runs out of memory.

**Solution 2/2**
Set `LogSizeLimit:104857600`

**Comment by agtogna** [comment]
For Issue 2/2 we disabled the Log file completely, now we log on stdout only (k8s style)

**Comment by agtogna** [comment]
For Issue 1/2
the problem surfaces if `Version` is not defined or if `Version`<4
we are now clearly setting the `Version` in the values
